import { ButtonSizeType, ISizes } from "../theme.interface";

const giantButtonSize: ButtonSizeType = {
  fontSize: "18px",
  iconFontSize: "17px",
  iconHeight: "21px",
  iconWidth: "20px",
  iconLineHeight: "24px",
  lineHeight: "1.33",
  padding: "16px 22px",
  paddingFromIcon: "10px",
  paddingWithLeftIcon: "16px 22px 16px 16px",
  paddingWithRightIcon: "16px 18px 16px 22px",
  squarePadding: "14px",
  squareWidth: "56px",
};

export const sizes: ISizes = {
  button: {
    giant: giantButtonSize,
    large: {
      ...giantButtonSize,
      fontSize: "16px",
      iconLineHeight: "24px",
      lineHeight: "1.25",
      padding: "14px 18px",
      paddingFromIcon: "12px",
      paddingWithLeftIcon: "12px 18px 12px 14px",
      paddingWithRightIcon: "12px 15px 12px 22px",
      squarePadding: "12px",
      squareWidth: "48px",
    },
    medium: {
      fontSize: "14px",
      iconFontSize: "14px",
      iconHeight: "17px",
      iconWidth: "17px",
      iconLineHeight: "20px",
      lineHeight: "1.14",
      padding: "12px 18px 12px 19px",
      paddingFromIcon: "4.5px",
      paddingWithLeftIcon: "10px 18.5px 10px 16px",
      paddingWithRightIcon: "10px 16.5px 10px 13px",
      squarePadding: "10px",
      squareWidth: "40px",
    },
    small: {
      fontSize: "12px",
      iconFontSize: "11px",
      iconHeight: "14px",
      iconWidth: "14px",
      iconLineHeight: "16px",
      lineHeight: "1.33",
      padding: "8px 14px 8px 15px",
      paddingFromIcon: "2.5px",
      paddingWithLeftIcon: "8px 14.5px 8px 11px",
      paddingWithRightIcon: "8px 8px 8px 12.5px",
      squarePadding: "8px",
      squareWidth: "32px",
    },
    tiny: {
      fontSize: "10px",
      iconFontSize: "9px",
      iconHeight: "11px",
      iconWidth: "11px",
      iconLineHeight: "12px",
      lineHeight: "1.2",
      padding: "6px 11px",
      paddingFromIcon: "7px",
      paddingWithLeftIcon: "6px 11px 6px 8px",
      paddingWithRightIcon: "6px 9px 6px 13px",
      squarePadding: "6px",
      squareWidth: "24px",
    },
  },
  frame: {
    smartphone: {
      width: "338px",
      height: "690px",
      padding: "13px",
      screenPadding: "40px 16px 16px",
      borderRadius: "40px",
      screenBorderRadius: "30px",
      cameraSize: "10px",
      topBangsPadding: "15px",
    },
    tablet: {
      width: "605px",
      height: "725px",
      padding: "23px",
      screenPadding: "24px 16px",
      borderRadius: "36px",
      screenBorderRadius: "20px",
      cameraSize: "11px",
      topBangsPadding: "6px",
    },
  },
  imagePickerDefaultSize: {
    width: "96px",
    height: "96px",
    borderRadius: "4px",
    closeIconSize: "22px",
  },
  snackbar: {
    fontSize: "15px",
  },
  contentBox: {
    defaultPaddings: "62px 80px 80px",
    defaultWidth: "560px",
  },
  formFooter: {
    marginTop: "16px",
    fontSize: "12px",
  },
  questionCard: {
    actionItem: {
      fontSize: "12px",
      lineHeight: "normal",
      iconSize: 24,
      marginLeft: "10px",
      marginRight: "10px",
    },
    actions: {
      height: "50px",
      left: {
        padding: "0",
      },
      padding: "5px 0 0",
      right: {
        padding: "0 25px",
      },
    },
    content: {
      padding: "20px",
    },
    iconButton: {
      marginLeft: "10px",
      marginRight: "10px",
      marginTop: "5px",
      marginBottom: "auto",
    },
  },
};
